/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearanceSettings: typeof import('./components/settings/AppearanceSettings.vue')['default']
    Avatar: typeof import('./components/chat/avatar.vue')['default']
    ChatDetail: typeof import('./components/chat/ChatDetail/index.vue')['default']
    ChatList: typeof import('./components/chat/ChatList.vue')['default']
    ContactList: typeof import('./components/chat/ContactList.vue')['default']
    Header: typeof import('./components/chat/ChatDetail/Header.vue')['default']
    MessageContent: typeof import('./components/chat/ChatDetail/MessageContent.vue')['default']
    MessageInput: typeof import('./components/chat/ChatDetail/MessageInput.vue')['default']
    OldChatDetail: typeof import('./components/chat/oldChatDetail.vue')['default']
    ResizableLayout: typeof import('./components/layout/ResizableLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsList: typeof import('./components/chat/SettingsList.vue')['default']
    SideNavBar: typeof import('./components/layout/SideNavBar.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}
