/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearanceSettings: typeof import('./components/settings/AppearanceSettings.vue')['default']
    AudioPlayerCore: typeof import('./components/audio/AudioPlayerCore.vue')['default']
    Avatar: typeof import('./components/chat/avatar.vue')['default']
    ChatDetail: typeof import('./components/chat/ChatDetail/index.vue')['default']
    ChatList: typeof import('./components/chat/ChatList.vue')['default']
    ChatTypeToggle: typeof import('./components/settings/ChatTypeToggle.vue')['default']
    CollapsibleSection: typeof import('./components/settings/CollapsibleSection.vue')['default']
    ContactList: typeof import('./components/chat/ContactList.vue')['default']
    CustomEmojiInline: typeof import('./components/chat/ChatDetail/MessageContent/CustomEmojiInline.vue')['default']
    DownloadSettings: typeof import('./components/settings/DownloadSettings.vue')['default']
    FormattedTextInline: typeof import('./components/chat/FormattedTextInline.vue')['default']
    ForumTopicList: typeof import('./components/chat/ForumTopicList.vue')['default']
    Header: typeof import('./components/chat/ChatDetail/Header.vue')['default']
    MediaViewer: typeof import('./components/chat/ChatDetail/MessageContent/MediaViewer.vue')['default']
    MessageAlbum: typeof import('./components/chat/ChatDetail/MessageContent/MessageAlbum.vue')['default']
    MessageContent: typeof import('./components/chat/ChatDetail/MessageContent/index.vue')['default']
    MessageFileContent: typeof import('./components/chat/ChatDetail/MessageContent/MessageFileContent.vue')['default']
    MessageInput: typeof import('./components/chat/ChatDetail/MessageInput.vue')['default']
    MessageMediaContent: typeof import('./components/chat/ChatDetail/MessageContent/MessageMediaContent.vue')['default']
    MessageOtherContent: typeof import('./components/chat/ChatDetail/MessageContent/MessageOtherContent.vue')['default']
    MessageReply: typeof import('./components/chat/ChatDetail/MessageContent/MessageReply.vue')['default']
    MessageRichMessage: typeof import('./components/chat/ChatDetail/MessageContent/MessageRichMessage.vue')['default']
    MessageServiceContent: typeof import('./components/chat/ChatDetail/MessageContent/MessageServiceContent.vue')['default']
    MessageStatus: typeof import('./components/chat/ChatDetail/MessageContent/MessageStatus.vue')['default']
    MessageStickerContent: typeof import('./components/chat/ChatDetail/MessageContent/MessageStickerContent.vue')['default']
    MessageTextContent: typeof import('./components/chat/ChatDetail/MessageContent/MessageTextContent.vue')['default']
    MessageVoiceContent: typeof import('./components/chat/ChatDetail/MessageContent/MessageVoiceContent.vue')['default']
    MusicPlayerEntry: typeof import('./components/audio/MusicPlayerEntry.vue')['default']
    MusicPlayerOverlay: typeof import('./components/audio/MusicPlayerOverlay.vue')['default']
    OldChatDetail: typeof import('./components/chat/oldChatDetail.vue')['default']
    PinnedMessageBar: typeof import('./components/chat/ChatDetail/PinnedMessageBar.vue')['default']
    ResizableLayout: typeof import('./components/layout/ResizableLayout.vue')['default']
    RichCaption: typeof import('./components/chat/ChatDetail/MessageContent/RichCaption.vue')['default']
    RichImage: typeof import('./components/chat/ChatDetail/MessageContent/RichImage.vue')['default']
    RichText: typeof import('./components/chat/ChatDetail/MessageContent/RichText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsList: typeof import('./components/chat/SettingsList.vue')['default']
    SideNavBar: typeof import('./components/layout/SideNavBar.vue')['default']
    SwipeActions: typeof import('./components/chat/SwipeActions.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
    ToggleSwitch: typeof import('./components/settings/ToggleSwitch.vue')['default']
    TOption: typeof import('tdesign-vue-next')['Option']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}
